---

############################
##### Clone Repository #####
############################

- name: Copy SSH Key - Private
  copy: src={{ git_repo_ssh_private_key }} dest=/home/{{ ansible_ssh_user }}/.ssh/{{ git_repo_name }}_rsa owner={{ ansible_ssh_user }} group=sudo mode=0600
  become: no
  when: git_repo_ssh_private_key != false

- name: Copy SSH Key - Public
  copy: src={{ git_repo_ssh_public_key }} dest=/home/{{ ansible_ssh_user }}/.ssh/{{ git_repo_name }}_rsa.pub owner={{ ansible_ssh_user }} group=sudo mode=0644
  become: no
  when: git_repo_ssh_public_key != false

- name: Clone Git repo (Private)
  git: repo={{ git_repo_url }} dest=/home/{{ ansible_ssh_user }}/{{ git_repo_name }} force=yes accept_hostkey=yes key_file=/home/{{ ansible_ssh_user }}/.ssh/{{ git_repo_name }}_rsa
  become: no
  register: gitcode
  when: git_repo_ssh_private_key != false

- name: Run Command (e.g. for Building)
  become: no
  command: "{{ git_repo_command }}"
  args:
    chdir: /home/{{ ansible_ssh_user }}/{{ git_repo_name }}
  when: gitcode.changed and git_repo_command != false

- name: Clone Git Repository (Public)
  git: repo={{ git_repo_url }} dest=/home/{{ ansible_ssh_user }}/{{ git_repo_name }} force=yes accept_hostkey=yes
  become: no
  register: gitcode
  when: git_repo_ssh_private_key == false

- name: Run Command (e.g. for Building)
  become: no
  command: "{{ git_repo_command }}"
  args:
    chdir: /home/{{ ansible_ssh_user }}/{{ git_repo_name }}
  when: gitcode.changed and git_repo_command != false

- name: Correct Permissions for Directory
  become: yes
  file: path=/home/{{ ansible_ssh_user }}/{{ git_repo_name }} state=directory owner={{ ansible_ssh_user }} group=sudo mode=0755

# TODO: Might have been fixed in Ansible v2. Disabled
# Workaround
#- name: Configure Git
#  shell: chdir="/home/{{ ansible_ssh_user }}/{{ git_repo_name }}" git config url."https://".insteadOf git://;
#  become: no
#  when: gitcode.changed

